### ISSUE TITLE
[FEAT] 게시물 좋아요 API 구현

### ISSUE THREAD

**Issue by TirTir** [PreOnboarding-Team-11/socialFeed#32]
## 📖 Describe
> 게시물 좋아요 API 구현

## ✅ TODO
- [x] like_count관리 로직 설계
- [x] API Controller 작성
- [x] type URL 생성
- [x] 외부 API 호출

## 참고(선택)
> 참고자료
